/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=workers/mastra-agent/wrangler.jsonc --include-runtime=false workers/mastra-agent/worker-configuration.d.ts` (hash: 32237e96c4e113b4d2ff62eafbcf73ef)
interface __BaseEnv_Env {
	WORKBOOKS: R2Bucket;
	DB: D1Database;
	AI: Ai;
	AGENT_ENV: "production";
	MASTRA_MODEL: "openai/gpt-5.6-luna";
	CLOUDFLARE_ACCOUNT_ID: "ec3c6c647b0cb93c9a237028f499f427";
	WEB_SEARCH_MODEL: "openai/gpt-4o-mini";
	AI_GATEWAY_ID: "default";
	WEB_SEARCH_MAX_TOOL_CALLS: "3";
	WEB_SEARCH_TIMEOUT_MS: "15000";
	SPREADSHEET_MAX_ROWS: "50";
	WORKBOOK_EDITING_ENABLED: "false";
	AGENT_REQUEST_TIMEOUT_MS: "90000";
	AGENT_ANSWER_TIMEOUT_MS: "45000";
	ALLOWED_ORIGINS: "https://www.excelgen.app";
	MAX_UPLOAD_BYTES: "20971520";
	AGENT_TOKEN_SECRET: string;
	LOCAL_BILLING_ENABLED: string;
	CLOUDFLARE_API_TOKEN: string;
	EXCEL_AGENT_WORKFLOW: Workflow<Parameters<import("./src/index").ExcelAgentWorkflow['run']>[0]['payload']>;
	SPREADSHEET_GENERATION_WORKFLOW: Workflow<Parameters<import("./src/index").SpreadsheetGenerationWorkflow['run']>[0]['payload']>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "AGENT_ENV" | "MASTRA_MODEL" | "CLOUDFLARE_ACCOUNT_ID" | "WEB_SEARCH_MODEL" | "AI_GATEWAY_ID" | "WEB_SEARCH_MAX_TOOL_CALLS" | "WEB_SEARCH_TIMEOUT_MS" | "SPREADSHEET_MAX_ROWS" | "WORKBOOK_EDITING_ENABLED" | "AGENT_REQUEST_TIMEOUT_MS" | "AGENT_ANSWER_TIMEOUT_MS" | "ALLOWED_ORIGINS" | "MAX_UPLOAD_BYTES" | "AGENT_TOKEN_SECRET" | "LOCAL_BILLING_ENABLED" | "CLOUDFLARE_API_TOKEN">> {}
}
